spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:4306/rt?characterEncodingUTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root
    hikari:
      maximum-pool-size: 10

decorator:
  datasource:
    p6spy:
      enable-logging: on
      multiline: true